telefon: "05153 1552"
telefon_link: "051531552"
email: "info@andreasdevries.de"
strasse: "An den Flachsrotten 2"
plz_ort: "31020 Salzhemmendorf"
oeffnungszeiten: |
  Montag – Freitag
  8:00 bis 16:00 Uhr
